### ISSUE TITLE
Add a background dim

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Wordle-in-JS#1]
When the "How to play" is clicked and the instruction modal appears, there is no difference between the shades of the modal and the rest of the page. Apply a dimming effect to the rest of the page which switches when the modal appears/disappears.

**Comment by Chetax** [comment]
Hello @swagatmitra-b ! Just a quick heads up. I'm interested in solving this :D Can You Please Assign Me.

**Comment by Chetax** [comment]
@swagatmitra-b  can you please look on my pr...it write or what changes should i do please
