### ISSUE TITLE
Fix duplicate entries being accepted 

### ISSUE THREAD

**Issue by swagatmitra-b** [swagatmitra-b/Wordle-in-JS#2]
If a letter is highlighted green or blue in the first random guess, and the same letter is entered in all cells in every subsequent guess, all cells will be marked green or blue even though the correct word most obviously does not consist of the same repeating letter.

**Comment by debsouryadatta** [comment]
Hii @swagatmitra-b 👋, please assign me this issue under hacktoberfest.
